INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Madrid', 'Biblioteca Nacional de España', '1712-12-29', 30000000, 'La Biblioteca Nacional de España es un centro bibliográfico español que tiene por objetivo reunir, catalogar y conservar fondos bibliográficos, así como promover la investigación y difundir la información bibliográfica.', 'https://www.bne.es');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Barcelona', 'Biblioteca de Catalunya', '1907-07-24', 3000000, 'La Biblioteca de Catalunya es la biblioteca nacional de Cataluña y una de las más importantes de España. Conserva el patrimonio bibliográfico y documental catalán.', 'https://www.bnc.cat');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Sevilla', 'Biblioteca Provincial de Sevilla', '1932-06-15', 250000, 'Biblioteca pública provincial ubicada en el centro de Sevilla, con una amplia colección de obras clásicas y contemporáneas.', 'https://www.juntadeandalucia.es/cultura/bibliotecas');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Valencia', 'Biblioteca Valenciana', '1985-11-20', 1500000, 'Biblioteca patrimonial de la Comunidad Valenciana que custodia el patrimonio bibliográfico y documental valenciano.', 'https://www.bv.gva.es');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Bilbao', 'Biblioteca Foral de Bizkaia', '1924-03-10', 500000, 'Una de las bibliotecas más importantes del País Vasco, con una importante colección de obras en euskera y castellano.', 'https://www.bizkaia.eus/biblioteca');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Santiago de Compostela', 'Biblioteca Xeral de la Universidad de Santiago', '1495-09-02', 2000000, 'Biblioteca universitaria histórica con fondos antiguos de gran valor patrimonial y una moderna colección académica.', 'https://www.usc.gal/biblioteca');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Zaragoza', 'Biblioteca Pública de Zaragoza', '1844-05-18', 450000, 'Biblioteca provincial que ofrece servicios de préstamo, sala de lectura y actividades culturales para toda la comunidad.', 'https://www.dpz.es/cultura/bibliozgz');
INSERT INTO biblioteca (city_name, library_name, foundation_date, num_books, description, url) VALUES ('Salamanca', 'Biblioteca General Histórica de la Universidad', '1254-01-01', 1800000, 'Una de las bibliotecas universitarias más antiguas de Europa, con incunables y manuscritos medievales de gran valor.', 'https://bibliotecas.usal.es');

